# Avalanche accidents 2

In [6]:
import pandas as pd
import numpy as np

In [7]:
with open("lawinenunfälle_seit_1970.csv", "r", encoding="utf-8") as f:
    f.readline()
    f.readline()
    f.readline()
    columns = f.readline().strip().strip('"').split(",")

df = pd.read_csv(
    r"C:\Users\david\Desktop\Uni Zürich\VWL\9. Semester\Data Analysis with Python\Woche 5\lawinenunfälle_seit_1970.csv",
    skiprows=4,
    header=None,
    names=columns
)
df.head()

,avalanche.id,date,date.quality,hydrological.year,canton,municipality,"""""start.zone.coordinates.latitude""""","""""start.zone.coordinates.longitude""""",coordinates.quality,start.zone.elevation,...,start.zone.inclination,"""""forecasted.dangerlevel.rating1""""","""""forecasted.dangerlevel.rating1.subdivision""""","""""forecasted.dangerlevel.rating2""""","""""forecasted.dangerlevel.rating2.subdivision""""","""""forecasted.most.dangerous.aspect.and.elevation""""",number.dead,number.caught,number.fully.buried,activity
0,afbfcea9-91d4-441d-ba46-c51304b608ed,1970-10-05,0.0,1970/71,BE,Guttannen,46.575365,8.339613,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,0.0,transportation.corridor
1,861431db-0239-4e52-b706-874356ac4e89,1970-10-23,0.0,1970/71,UR,Realp,46.574945,8.413497,0.0,2600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,1.0,transportation.corridor
2,094f1b42-4a6f-4388-911e-6d2f85437099,1970-12-27,0.0,1970/71,SG,Mels,46.958531,9.387519,0.0,2770.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,tour
3,13d285cd-c1a6-4f2d-acd6-45d972a45e47,1970-12-28,0.0,1970/71,SG,Grabs,47.157480,9.330461,100.0,1980.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,tour
4,d248b0f6-70f5-49b1-bf5f-0147fcc05555,1971-01-03,0.0,1970/71,GR,Davos,46.699354,9.923595,0.0,2470.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,tour

# Preparation phase

In [8]:
df.shape

(4868, 21)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4868 entries, 0 to 4867
Data columns (total 21 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   avalanche.id                                        4868 non-null   str
 1   date                                                4297 non-null   str
 2   date.quality                                        4260 non-null   float64
 3   hydrological.year                                   4297 non-null   str
 4   canton                                              4296 non-null   str
 5   municipality                                        4296 non-null   str
 6   ""start.zone.coordinates.latitude""                 4297 non-null   float64
 7   ""start.zone.coordinates.longitude""                4297 non-null   float64
 8   coordinates.quality                                 4016 non-null   float64
 9   start.zone.elevation                                4102 non-null   float64
 10  start.zone.slope.aspect                             4088 non-null   str
 11  start.zone.inclination                              2318 non-null   str
 12  ""forecasted.dangerlevel.rating1""                  2511 non-null   float64
 13  ""forecasted.dangerlevel.rating1.subdivision""      274 non-null    str
 14  ""forecasted.dangerlevel.rating2""                  193 non-null    float64
 15  ""forecasted.dangerlevel.rating2.subdivision""      0 non-null      float64
 16  ""forecasted.most.dangerous.aspect.and.elevation""  2511 non-null   object
 17  number.dead                                         4297 non-null   float64
 18  number.caught                                       4297 non-null   float64
 19  number.fully.buried                                 4297 non-null   float64
 20  activity                                            4182 non-null   str
dtypes: float64(11), object(1), str(9)
memory usage: 1.2+ MB

In [10]:
df.describe()

,date.quality,"""""start.zone.coordinates.latitude""""","""""start.zone.coordinates.longitude""""",coordinates.quality,start.zone.elevation,"""""forecasted.dangerlevel.rating1""""","""""forecasted.dangerlevel.rating2""""","""""forecasted.dangerlevel.rating2.subdivision""""",number.dead,number.caught,number.fully.buried
count,4260.000000,4297.000000,4297.000000,4016.000000,4102.000000,2511.00000,193.000000,0.0,4297.000000,4297.000000,4297.000000
mean,0.054460,46.516031,8.558556,65.351096,2463.328376,2.63640,2.549223,NaN,0.284152,1.889690,0.506167
std,2.854595,0.318635,1.054301,148.597516,468.394040,0.60576,0.539011,NaN,0.707115,2.794552,0.963013
min,0.000000,45.859427,6.111343,0.000000,725.000000,1.00000,2.000000,NaN,0.000000,1.000000,0.000000
25%,0.000000,46.240390,7.546600,0.000000,2160.000000,2.00000,2.000000,NaN,0.000000,1.000000,0.000000
50%,0.000000,46.547004,8.467632,0.000000,2460.000000,3.00000,3.000000,NaN,0.000000,1.000000,0.000000
75%,0.000000,46.775089,9.713406,100.000000,2740.000000,3.00000,3.000000,NaN,0.000000,2.000000,1.000000
max,186.000000,47.318149,10.475355,5000.000000,4389.000000,4.00000,4.000000,NaN,11.000000,137.000000,12.000000

In [11]:
# rename columns
df = df.rename(columns={
    "avalanche.id": "avalanche_id",
    "date.quality": "date_quality",
    "hydrological.year": "hydrological_year",
    '""start.zone.coordinates.latitude""': "latitude",
    '""start.zone.coordinates.longitude""': "longitude",
    "start.zone.elevation": "elevation",
    "start.zone.slope.aspect": "slope_aspect",
    "start.zone.inclination": "inclination",
    "number.dead": "deaths",
    "number.caught": "caught",
    "number.fully.buried": "fully_buried",
    "activity": "activity",
    '""forecasted.dangerlevel.rating1""': "dangerlevel_rating1",
    '""forecasted.dangerlevel.rating1.subdivision""': "dangerlevel_rating1_subdivision",
    '""forecasted.dangerlevel.rating2""': "dangerlevel_rating2",
    '""forecasted.most.dangerous.aspect.and.elevation""': "most_dangerous_aspect_and_elevation"
})
df.columns

Index(['avalanche_id', 'date', 'date_quality', 'hydrological_year', 'canton',
       'municipality', 'latitude', 'longitude', 'coordinates.quality',
       'elevation', 'slope_aspect', 'inclination', 'dangerlevel_rating1',
       'dangerlevel_rating1_subdivision', 'dangerlevel_rating2',
       '""forecasted.dangerlevel.rating2.subdivision""',
       'most_dangerous_aspect_and_elevation', 'deaths', 'caught',
       'fully_buried', 'activity'],
      dtype='str')

# Filtering phase - row operations

In [12]:
# drop empty column
df = df.drop(columns=['""forecasted.dangerlevel.rating2.subdivision""'], errors="ignore")

In [13]:
# control
df.columns

Index(['avalanche_id', 'date', 'date_quality', 'hydrological_year', 'canton',
       'municipality', 'latitude', 'longitude', 'coordinates.quality',
       'elevation', 'slope_aspect', 'inclination', 'dangerlevel_rating1',
       'dangerlevel_rating1_subdivision', 'dangerlevel_rating2',
       'most_dangerous_aspect_and_elevation', 'deaths', 'caught',
       'fully_buried', 'activity'],
      dtype='str')

In [14]:
# count missing values
df.isna().sum()

avalanche_id                              0
date                                    571
date_quality                            608
hydrological_year                       571
canton                                  572
municipality                            572
latitude                                571
longitude                               571
coordinates.quality                     852
elevation                               766
slope_aspect                            780
inclination                            2550
dangerlevel_rating1                    2357
dangerlevel_rating1_subdivision        4594
dangerlevel_rating2                    4675
most_dangerous_aspect_and_elevation    2357
deaths                                  571
caught                                  571
fully_buried                            571
activity                                686
dtype: int64

# research question: Are certain terrain characteristics associated with more severe avalanche accidents?

In [15]:
# copy data frame
df_terrain = df.loc[:, [
    "avalanche_id",
    "date",
    "canton",
    "elevation",
    "slope_aspect",
    "inclination",
    "dangerlevel_rating1",
    "dangerlevel_rating1_subdivision",
    "dangerlevel_rating2",
    "deaths",
    "caught",
    "fully_buried",
    "activity"
]].copy()
df_terrain.head()

,avalanche_id,date,canton,elevation,slope_aspect,inclination,dangerlevel_rating1,dangerlevel_rating1_subdivision,dangerlevel_rating2,deaths,caught,fully_buried,activity
0,afbfcea9-91d4-441d-ba46-c51304b608ed,1970-10-05,BE,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,0.0,transportation.corridor
1,861431db-0239-4e52-b706-874356ac4e89,1970-10-23,UR,2600.0,SE,NaN,NaN,NaN,NaN,1.0,5.0,1.0,transportation.corridor
2,094f1b42-4a6f-4388-911e-6d2f85437099,1970-12-27,SG,2770.0,NE,NaN,NaN,NaN,NaN,0.0,1.0,1.0,tour
3,13d285cd-c1a6-4f2d-acd6-45d972a45e47,1970-12-28,SG,1980.0,NW,NaN,NaN,NaN,NaN,1.0,1.0,1.0,tour
4,d248b0f6-70f5-49b1-bf5f-0147fcc05555,1971-01-03,GR,2470.0,NW,NaN,NaN,NaN,NaN,1.0,1.0,1.0,tour

In [16]:
# missing values for the relevant variables
df_terrain.isna().sum()

avalanche_id                          0
date                                571
canton                              572
elevation                           766
slope_aspect                        780
inclination                        2550
dangerlevel_rating1                2357
dangerlevel_rating1_subdivision    4594
dangerlevel_rating2                4675
deaths                              571
caught                              571
fully_buried                        571
activity                            686
dtype: int64

In [17]:
# show missing values as a percentage
missing_percent = (df_terrain.isna().mean() * 100)
print(missing_percent)

avalanche_id                        0.000000
date                               11.729663
canton                             11.750205
elevation                          15.735415
slope_aspect                       16.023007
inclination                        52.382909
dangerlevel_rating1                48.418242
dangerlevel_rating1_subdivision    94.371405
dangerlevel_rating2                96.035333
deaths                             11.729663
caught                             11.729663
fully_buried                       11.729663
activity                           14.092030
dtype: float64

In [18]:
# fill in missing values for inclination
df_terrain["inclination"] = (df_terrain["inclination"].fillna("Unknown"))

In [19]:
# test for duplicates
print(df_terrain.duplicated().sum())
print(df_terrain["avalanche_id"].duplicated().sum())

0
0

# Cleaning phase

In [ ]:
# check types
df_terrain.dtypes

avalanche_id                                  str
date                               datetime64[us]
canton                                        str
elevation                                 float64
slope_aspect                                  str
inclination                                   str
dangerlevel_rating1                       float64
dangerlevel_rating1_subdivision               str
dangerlevel_rating2                       float64
deaths                                    float64
caught                                    float64
fully_buried                              float64
activity                                      str
dtype: object

In [34]:
# to datetime 
df_terrain["date"] = pd.to_datetime(df_terrain["date"], errors="coerce")
df_terrain.head()

,avalanche_id,date,canton,elevation,slope_aspect,inclination,dangerlevel_rating1,dangerlevel_rating1_subdivision,dangerlevel_rating2,deaths,caught,fully_buried,activity
0,afbfcea9-91d4-441d-ba46-c51304b608ed,1970-10-05,BE,NaN,NaN,Unknown,NaN,NaN,NaN,0.0,3.0,0.0,transportation.corridor
1,861431db-0239-4e52-b706-874356ac4e89,1970-10-23,UR,2600.0,SE,Unknown,NaN,NaN,NaN,1.0,5.0,1.0,transportation.corridor
2,094f1b42-4a6f-4388-911e-6d2f85437099,1970-12-27,SG,2770.0,NE,Unknown,NaN,NaN,NaN,0.0,1.0,1.0,tour
3,13d285cd-c1a6-4f2d-acd6-45d972a45e47,1970-12-28,SG,1980.0,NW,Unknown,NaN,NaN,NaN,1.0,1.0,1.0,tour
4,d248b0f6-70f5-49b1-bf5f-0147fcc05555,1971-01-03,GR,2470.0,NW,Unknown,NaN,NaN,NaN,1.0,1.0,1.0,tour

In [ ]:
# to category
df_terrain["inclination"].value_counts(dropna=False)
df_terrain["inclination"] = (df_terrain["inclination"].astype("category"))

In [ ]:
# to category
df_terrain["slope_aspect"].value_counts(dropna=False)
df_terrain["slope_aspect"] = (df_terrain["slope_aspect"].astype("category"))

In [31]:
df_terrain[["elevation", "deaths", "caught", "fully_buried"]].describe()

         elevation       deaths       caught  fully_buried
count  4102.000000  4297.000000  4297.000000   4297.000000
mean   2463.328376     0.284152     1.889690      0.506167
std     468.394040     0.707115     2.794552      0.963013
min     725.000000     0.000000     1.000000      0.000000
25%    2160.000000     0.000000     1.000000      0.000000
50%    2460.000000     0.000000     1.000000      0.000000
75%    2740.000000     0.000000     2.000000      1.000000
max    4389.000000    11.000000   137.000000     12.000000

In [33]:
# check unusual value (max 137 caught)
df_terrain.nlargest(1, "caught")

,avalanche_id,date,canton,elevation,slope_aspect,inclination,dangerlevel_rating1,dangerlevel_rating1_subdivision,dangerlevel_rating2,deaths,caught,fully_buried,activity
729,9346dcb8-c98c-4985-bb47-d0c587fa83d6,1988-03-20,BE,1580.0,W,Unknown,NaN,NaN,NaN,0.0,137.0,0.0,transportation.corridor

In [36]:
df_terrain.dtypes

avalanche_id                                  str
date                               datetime64[us]
canton                                        str
elevation                                 float64
slope_aspect                             category
inclination                              category
dangerlevel_rating1                       float64
dangerlevel_rating1_subdivision               str
dangerlevel_rating2                       float64
deaths                                    float64
caught                                    float64
fully_buried                              float64
activity                                      str
dtype: object