In [1]:
import pandas as pd
import numpy as np
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.5
NumPy: 2.5.3

In [2]:
with open("lawinenunfälle_seit_1970.csv", "r", encoding="utf-8") as f:
    f.readline()
    f.readline()
    f.readline()
    columns = f.readline().strip().strip('"').split(",")

print(columns)

df = pd.read_csv(
    "lawinenunfälle_seit_1970.csv",
    skiprows=4,
    header=None,
    names=columns
)
df.head()

['avalanche.id', 'date', 'date.quality', 'hydrological.year', 'canton', 'municipality', '""start.zone.coordinates.latitude""', '""start.zone.coordinates.longitude""', 'coordinates.quality', 'start.zone.elevation', 'start.zone.slope.aspect', 'start.zone.inclination', '""forecasted.dangerlevel.rating1""', '""forecasted.dangerlevel.rating1.subdivision""', '""forecasted.dangerlevel.rating2""', '""forecasted.dangerlevel.rating2.subdivision""', '""forecasted.most.dangerous.aspect.and.elevation""', 'number.dead', 'number.caught', 'number.fully.buried', 'activity']

,avalanche.id,date,date.quality,hydrological.year,canton,municipality,"""""start.zone.coordinates.latitude""""","""""start.zone.coordinates.longitude""""",coordinates.quality,start.zone.elevation,...,start.zone.inclination,"""""forecasted.dangerlevel.rating1""""","""""forecasted.dangerlevel.rating1.subdivision""""","""""forecasted.dangerlevel.rating2""""","""""forecasted.dangerlevel.rating2.subdivision""""","""""forecasted.most.dangerous.aspect.and.elevation""""",number.dead,number.caught,number.fully.buried,activity
0,afbfcea9-91d4-441d-ba46-c51304b608ed,1970-10-05,0.0,1970/71,BE,Guttannen,46.575365,8.339613,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,0.0,transportation.corridor
1,861431db-0239-4e52-b706-874356ac4e89,1970-10-23,0.0,1970/71,UR,Realp,46.574945,8.413497,0.0,2600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,1.0,transportation.corridor
2,094f1b42-4a6f-4388-911e-6d2f85437099,1970-12-27,0.0,1970/71,SG,Mels,46.958531,9.387519,0.0,2770.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,tour
3,13d285cd-c1a6-4f2d-acd6-45d972a45e47,1970-12-28,0.0,1970/71,SG,Grabs,47.157480,9.330461,100.0,1980.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,tour
4,d248b0f6-70f5-49b1-bf5f-0147fcc05555,1971-01-03,0.0,1970/71,GR,Davos,46.699354,9.923595,0.0,2470.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,tour

In [3]:
df.shape

(4868, 21)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4868 entries, 0 to 4867
Data columns (total 21 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   avalanche.id                                        4868 non-null   str
 1   date                                                4297 non-null   str
 2   date.quality                                        4260 non-null   float64
 3   hydrological.year                                   4297 non-null   str
 4   canton                                              4296 non-null   str
 5   municipality                                        4296 non-null   str
 6   ""start.zone.coordinates.latitude""                 4297 non-null   float64
 7   ""start.zone.coordinates.longitude""                4297 non-null   float64
 8   coordinates.quality                                 4016 non-null   float64
 9   start.zone.elevation                                4102 non-null   float64
 10  start.zone.slope.aspect                             4088 non-null   str
 11  start.zone.inclination                              2318 non-null   str
 12  ""forecasted.dangerlevel.rating1""                  2511 non-null   float64
 13  ""forecasted.dangerlevel.rating1.subdivision""      274 non-null    str
 14  ""forecasted.dangerlevel.rating2""                  193 non-null    float64
 15  ""forecasted.dangerlevel.rating2.subdivision""      0 non-null      float64
 16  ""forecasted.most.dangerous.aspect.and.elevation""  2511 non-null   object
 17  number.dead                                         4297 non-null   float64
 18  number.caught                                       4297 non-null   float64
 19  number.fully.buried                                 4297 non-null   float64
 20  activity                                            4182 non-null   str
dtypes: float64(11), object(1), str(9)
memory usage: 1.2+ MB

In [5]:
pd.set_option("display.max_columns", 21)

In [7]:
df["activity"]

0       transportation.corridor
1       transportation.corridor
2                          tour
3                          tour
4                          tour
                 ...
4863                       tour
4864                       tour
4865                       tour
4866                       tour
4867                        NaN
Name: activity, Length: 4868, dtype: str

In [8]:
type(df["activity"])

pandas.Series

In [9]:
df[["activity", "canton"]]

                     activity canton
0     transportation.corridor     BE
1     transportation.corridor     UR
2                        tour     SG
3                        tour     SG
4                        tour     GR
...                       ...    ...
4863                     tour     BE
4864                     tour     VS
4865                     tour     BE
4866                     tour     VS
4867                      NaN    NaN

[4868 rows x 2 columns]

In [10]:
df.columns

Index(['avalanche.id', 'date', 'date.quality', 'hydrological.year', 'canton',
       'municipality', '""start.zone.coordinates.latitude""',
       '""start.zone.coordinates.longitude""', 'coordinates.quality',
       'start.zone.elevation', 'start.zone.slope.aspect',
       'start.zone.inclination', '""forecasted.dangerlevel.rating1""',
       '""forecasted.dangerlevel.rating1.subdivision""',
       '""forecasted.dangerlevel.rating2""',
       '""forecasted.dangerlevel.rating2.subdivision""',
       '""forecasted.most.dangerous.aspect.and.elevation""', 'number.dead',
       'number.caught', 'number.fully.buried', 'activity'],
      dtype='str')

In [13]:
df.iloc[0]

avalanche.id                                          afbfcea9-91d4-441d-ba46-c51304b608ed
date                                                                            1970-10-05
date.quality                                                                           0.0
hydrological.year                                                                  1970/71
canton                                                                                  BE
municipality                                                                     Guttannen
""start.zone.coordinates.latitude""                                              46.575365
""start.zone.coordinates.longitude""                                              8.339613
coordinates.quality                                                                    NaN
start.zone.elevation                                                                   NaN
start.zone.slope.aspect                                                                NaN
start.zone.inclination                                                                 NaN
""forecasted.dangerlevel.rating1""                                                     NaN
""forecasted.dangerlevel.rating1.subdivision""                                         NaN
""forecasted.dangerlevel.rating2""                                                     NaN
""forecasted.dangerlevel.rating2.subdivision""                                         NaN
""forecasted.most.dangerous.aspect.and.elevation""                                     NaN
number.dead                                                                            0.0
number.caught                                                                          3.0
number.fully.buried                                                                    0.0
activity                                                           transportation.corridor
Name: 0, dtype: object

In [14]:
df.iloc[[0, 1], 4]

0    BE
1    UR
Name: canton, dtype: str

In [15]:
df.loc[0]

avalanche.id                                          afbfcea9-91d4-441d-ba46-c51304b608ed
date                                                                            1970-10-05
date.quality                                                                           0.0
hydrological.year                                                                  1970/71
canton                                                                                  BE
municipality                                                                     Guttannen
""start.zone.coordinates.latitude""                                              46.575365
""start.zone.coordinates.longitude""                                              8.339613
coordinates.quality                                                                    NaN
start.zone.elevation                                                                   NaN
start.zone.slope.aspect                                                                NaN
start.zone.inclination                                                                 NaN
""forecasted.dangerlevel.rating1""                                                     NaN
""forecasted.dangerlevel.rating1.subdivision""                                         NaN
""forecasted.dangerlevel.rating2""                                                     NaN
""forecasted.dangerlevel.rating2.subdivision""                                         NaN
""forecasted.most.dangerous.aspect.and.elevation""                                     NaN
number.dead                                                                            0.0
number.caught                                                                          3.0
number.fully.buried                                                                    0.0
activity                                                           transportation.corridor
Name: 0, dtype: object

In [16]:
df["activity"].value_counts()

activity
tour                       2485
offpiste                   1394
transportation.corridor     268
building                     35
Name: count, dtype: int64

In [21]:
df.loc[[0, 1, 2], "activity"]
df.loc[0:2, "number.caught":"activity"]

   number.caught  number.fully.buried                 activity
0            3.0                  0.0  transportation.corridor
1            5.0                  1.0  transportation.corridor
2            1.0                  1.0                     tour